---
# AWS
aws_test_server_ip: 3.89.41.136

# SELENIUM WAITS
driver_wait_in_sec: !!int 5

# SELENIUM DRIVERS options
window_size: !!str window-size=1920,1080

# PATHs
path_to_chrome_driver: /usr/local/bin/chromedriver
path_to_safari_driver: /usr/bin/safaridriver
path_to_firefox_driver: /usr/local/bin/geckodriver

# ENV
env_options:
  prod:
    frontend_url: https://hb-beta.stage.sirenltd.dev/
    backend_url:
  test:
    frontend_url:
    backend_url:

# SELENOID
selenoid_options:
  chrome104:
    browserName: chrome
    browserVersion: !!str 104.0
    platformName: linux
    selenoid:options:
      enableVNC: !!bool False
      enableVideo: !!bool False
      videoName: chrome104.mp4
...

